details:
    page_title: The Dashboard
layout:
    - row_1_of_2:

        - col_1_of_3:
            - tile_template: pie_chart
              tile_id: finished
              title: Finished Build Distribution

        - col_1_of_3:
            - tile_template: just_value
              tile_id: builds
              title: Builds

        - col_1_of_3:
            - tile_template: big_value
              tile_id: unfinished
              title: Unfinished Builds


    - row_1_of_2:
        - col_1_of_3 flip-time-10:
            - tile_template: listing
              tile_id: builders
              title: Top Builders

            - tile_template: listing
              tile_id: projects
              title: Top Projects

        - col_1_of_3:
            - tile_template: bar_chart
              tile_id: fifteendays
              title: Last Fifteen Days

        - col_1_of_3:
            - tile_template: listing
              tile_id: other
              title: Stats